# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Learning/Logic/vivado/P2S/P2S.cache/wt [current_project]
set_property parent.project_path E:/Learning/Logic/vivado/P2S/P2S.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Learning/Logic/vivado/P2S/P2S.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Learning/Logic/vivado/P2S/P2S.srcs/sources_1/new/Shift64.v
  E:/Learning/Logic/vivado/P2S/P2S.srcs/sources_1/new/P2S.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top P2S -part xc7k160tfbg676-2L


write_checkpoint -force -noxdef P2S.dcp

catch { report_utilization -file P2S_utilization_synth.rpt -pb P2S_utilization_synth.pb }
