# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vivado/Exp13-WallClock/Exp13-WallClock.cache/wt [current_project]
set_property parent.project_path F:/vivado/Exp13-WallClock/Exp13-WallClock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/vivado/Exp13-WallClock/Exp13-WallClock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/vivado/Exp13-WallClock/Exp13-WallClock.srcs/sources_1/new/ms_1000.v
  F:/vivado/Exp13-WallClock/Exp13-WallClock.srcs/sources_1/new/count_60.v
  F:/vivado/Exp13-WallClock/Exp13-WallClock.srcs/sources_1/new/count_24.v
  F:/vivado/Exp13-WallClock/Exp13-WallClock.srcs/sources_1/new/clk_1ms.v
  F:/vivado/Exp13-WallClock/Exp13-WallClock.srcs/sources_1/new/Wall_CLOCK.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Wall_CLOCK -part xc7k160tfbg676-2L


write_checkpoint -force -noxdef Wall_CLOCK.dcp

catch { report_utilization -file Wall_CLOCK_utilization_synth.rpt -pb Wall_CLOCK_utilization_synth.pb }
