webtalk_init -webtalk_dir /home/lovesy/Documents/Learning/CA/EXP4_Vivado/EXP4_Vivado.sim/sim_1/behav/xsim/xsim.dir/SCPU_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Dec 25 19:09:56 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d1a39b8b-b178-45b8-8a41-1d7f0894e0b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "367c231455a74b4bbf68256a3568a2b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "142" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2637.335 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "22" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "185 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "24 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "412" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "27" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.91_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "230856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3290911553 -regid "" -xml /home/lovesy/Documents/Learning/CA/EXP4_Vivado/EXP4_Vivado.sim/sim_1/behav/xsim/xsim.dir/SCPU_test_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/lovesy/Documents/Learning/CA/EXP4_Vivado/EXP4_Vivado.sim/sim_1/behav/xsim/xsim.dir/SCPU_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/lovesy/Documents/Learning/CA/EXP4_Vivado/EXP4_Vivado.sim/sim_1/behav/xsim/xsim.dir/SCPU_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
