# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/Shana/Desktop/EXP5/vivado/vivado.cache/wt [current_project]
set_property parent.project_path D:/Users/Shana/Desktop/EXP5/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Users/Shana/Desktop/EXP5/vivado/vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Users/Shana/Desktop/EXP5/vivado/vivado.srcs/sources_1/ip/ROM_D/ROM.coe
add_files D:/Users/Shana/Desktop/EXP5/vivado/vivado.srcs/sources_1/ip/RAM_B/RAM.coe
read_verilog -library xil_defaultlib {
  D:/Users/Shana/Desktop/EXP5/GPIO.v
  D:/Users/Shana/Desktop/EXP5/Reg_32.v
  D:/Users/Shana/Desktop/EXP5/Regs_8_32.v
  D:/Users/Shana/Desktop/EXP5/Shift64.v
  D:/Users/Shana/Desktop/EXP5/counter_32bit_rev.v
  D:/Users/Shana/Desktop/EXP5/Reg_8bit.v
  D:/Users/Shana/Desktop/EXP5/Element/xor32.v
  D:/Users/Shana/Desktop/EXP5/Element/srl32.v
  D:/Users/Shana/Desktop/EXP5/Element/SignalExt_32.v
  {D:/Users/Shana/Desktop/EXP5/Element/or_bit_32 .v}
  D:/Users/Shana/Desktop/EXP5/Element/or32.v
  D:/Users/Shana/Desktop/EXP5/Element/nor32.v
  D:/Users/Shana/Desktop/EXP5/Element/MUX8T1_32.v
  D:/Users/Shana/Desktop/EXP5/Element/and32.v
  D:/Users/Shana/Desktop/EXP5/Element/addc_32.v
  D:/Users/Shana/Desktop/EXP5/regs.v
  D:/Users/Shana/Desktop/EXP5/REG32.v
  D:/Users/Shana/Desktop/EXP5/Hex2Seg.v
  D:/Users/Shana/Desktop/EXP5/Element/MUX2T1_5.v
  D:/Users/Shana/Desktop/EXP5/Element/MUX2T1_32.v
  D:/Users/Shana/Desktop/EXP5/Element/Ext_imm16.v
  D:/Users/Shana/Desktop/EXP5/Element/add_32.v
  D:/Users/Shana/Desktop/EXP5/SSeg_map.v
  D:/Users/Shana/Desktop/EXP5/Seg_map.v
  D:/Users/Shana/Desktop/EXP5/P2S_IO.v
  D:/Users/Shana/Desktop/EXP5/MUXHM.v
  D:/Users/Shana/Desktop/EXP5/MUX2T1_64.v
  D:/Users/Shana/Desktop/EXP5/LED_P2S_IO.v
  D:/Users/Shana/Desktop/EXP5/HexTo8SEG8.v
  D:/Users/Shana/Desktop/EXP5/SPIO.v
  D:/Users/Shana/Desktop/EXP5/SEnter_2_32_IO.v
  D:/Users/Shana/Desktop/EXP5/SAnti_jitter_IO.v
  D:/Users/Shana/Desktop/EXP5/PIO.v
  D:/Users/Shana/Desktop/EXP5/Multi_8CH32.v
  D:/Users/Shana/Desktop/EXP5/MIO_BUS_IO.v
  D:/Users/Shana/Desktop/EXP5/Counter_3_IO.v
  D:/Users/Shana/Desktop/EXP5/clkdiv.v
  D:/Users/Shana/Desktop/EXP5/MUX8T1_8.vf
  D:/Users/Shana/Desktop/EXP5/ScanSync.vf
  D:/Users/Shana/Desktop/EXP5/Data_path.vf
  D:/Users/Shana/Desktop/EXP5/Seg7_Dev.vf
  D:/Users/Shana/Desktop/EXP5/MC14495_ZJU.vf
  D:/Users/Shana/Desktop/EXP5/Display.vf
  D:/Users/Shana/Desktop/EXP5/Main.vf
  D:/Users/Shana/Desktop/EXP5/MUX4T1.vf
  D:/Users/Shana/Desktop/EXP5/ALU.vf
  D:/Users/Shana/Desktop/EXP5/SCPU.vf
  D:/Users/Shana/Desktop/EXP5/SCPU_ctrl.vf
}
read_ip -quiet D:/Users/Shana/Desktop/EXP5/vivado/vivado.srcs/sources_1/ip/ROM_D/ROM_D.xco
set_property is_locked true [get_files D:/Users/Shana/Desktop/EXP5/vivado/vivado.srcs/sources_1/ip/ROM_D/ROM_D.xco]

read_ip -quiet D:/Users/Shana/Desktop/EXP5/vivado/vivado.srcs/sources_1/ip/RAM_B/RAM_B.xco
set_property is_locked true [get_files D:/Users/Shana/Desktop/EXP5/vivado/vivado.srcs/sources_1/ip/RAM_B/RAM_B.xco]

read_edif D:/Users/Shana/Desktop/EXP5/MIO_BUS.ngc
read_edif D:/Users/Shana/Desktop/EXP5/Counter_x.ngc
read_edif D:/Users/Shana/Desktop/EXP5/SAnti_jitter.ngc
read_edif D:/Users/Shana/Desktop/EXP5/SEnter_2_32.ngc
read_edif D:/Users/Shana/Desktop/EXP5/P2S.ngc
read_edif D:/Users/Shana/Desktop/EXP5/LED_P2S.ngc
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Main -part xc7k160tfbg676-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
