# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/mouse/mouse.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mouse || ORIG_REF_NAME==mouse}]
