# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/Shana/Desktop/vivado/NestGather/NestGather.cache/wt [current_project]
set_property parent.project_path D:/Users/Shana/Desktop/vivado/NestGather/NestGather.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Users/Shana/Desktop/vivado/NestGather/NestGather.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/mouse.coe
add_files D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/bg.coe
add_files D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/Desktop/win.coe
add_files D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/Desktop/over.coe
add_files {{D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/New folder/startscreen.coe}}
add_files -quiet d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/winprompt/winprompt.dcp
set_property used_in_implementation false [get_files d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/winprompt/winprompt.dcp]
add_files -quiet d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/overprompt/overprompt.dcp
set_property used_in_implementation false [get_files d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/overprompt/overprompt.dcp]
add_files -quiet d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/startscreen/startscreen.dcp
set_property used_in_implementation false [get_files d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/startscreen/startscreen.dcp]
read_mem {
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell3.mif
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell2.mif
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell1.mif
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell4.mif
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell6.mif
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell5.mif
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/mif/cell0.mif
}
read_verilog -library xil_defaultlib {
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/tocell.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/chnest.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/initialNest.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/nestDisp.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/vgaSync.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/mouseDisp.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/clkdiv.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/readMouse.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/initMouse.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/mode.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/display.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/PS2Mouse.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/Main.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/nest.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/random.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/aroundCell.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/new/addMap.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/bcd2seg.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/startgame.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/endgame.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/prompt.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/sources_1/clk_1ms.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/sources_1/count_60.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/sources_1/ms_1000.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/bcd28seg.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/segdisp.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/sources_1/P2S_IO.v
  D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/new/tone.v
}
read_ip -quiet D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/mouse/mouse.xci
set_property used_in_implementation false [get_files -all d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/mouse/mouse_ooc.xdc]
set_property is_locked true [get_files D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/mouse/mouse.xci]

read_edif D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/imports/ip/P2S.ngc
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Main -part xc7k160tfbg676-2L


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
