# clk
set_property PACKAGE_PIN AC18 [get_ports {clk200P}]
set_property IOSTANDARD LVDS [get_ports {clk200P}]
set_property PACKAGE_PIN AD18 [get_ports {clk200N}]
set_property IOSTANDARD LVDS [get_ports {clk200N}]
#switch
set_property PACKAGE_PIN AA10 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[0]}]
set_property PACKAGE_PIN AB10 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[1]}]
set_property PACKAGE_PIN AA13 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[2]}]
set_property PACKAGE_PIN AA12 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[3]}]
set_property PACKAGE_PIN Y13 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[4]}]
set_property PACKAGE_PIN Y12 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[5]}]
set_property PACKAGE_PIN AD11 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[6]}]
set_property PACKAGE_PIN AD10 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[7]}]
set_property PACKAGE_PIN AE10 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[8]}]
set_property PACKAGE_PIN AE12 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[9]}]
set_property PACKAGE_PIN AF12 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[10]}]
set_property PACKAGE_PIN AE8 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[11]}]
set_property PACKAGE_PIN AF8 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[12]}]
set_property PACKAGE_PIN AE13 [get_ports {SW[13]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[13]}]
set_property PACKAGE_PIN AF13 [get_ports {SW[14]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[14]}]
set_property PACKAGE_PIN AF10 [get_ports {SW[15]}]
set_property IOSTANDARD LVCMOS15 [get_ports {SW[15]}]

#Inverse rest button
set_property PACKAGE_PIN W13 [get_ports RSTN]
set_property IOSTANDARD LVCMOS18 [get_ports RSTN]

##LED of Arduino
#set_property PACKAGE_PIN AB26 [get_ports {led[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
#set_property PACKAGE_PIN W24 [get_ports {led[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
#set_property PACKAGE_PIN W23 [get_ports {led[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
#set_property PACKAGE_PIN AB25 [get_ports {led[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
#set_property PACKAGE_PIN AA25 [get_ports {led[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
#set_property PACKAGE_PIN W21 [get_ports {led[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
#set_property PACKAGE_PIN V21 [get_ports {led[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
#set_property PACKAGE_PIN W26 [get_ports {led[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

#Buzzer
set_property PACKAGE_PIN AF24 [get_ports Buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports Buzzer]


#set_property PACKAGE_PIN AD21 [get_ports {segEn[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segEn[0]}]
#set_property PACKAGE_PIN AC21 [get_ports {segEn[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segEn[1]}]
#set_property PACKAGE_PIN AB21 [get_ports {segEn[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segEn[2]}]
#set_property PACKAGE_PIN AC22 [get_ports {segEn[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segEn[3]}]

#set_property PACKAGE_PIN AB22 [get_ports {segment[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[7]}]
#set_property PACKAGE_PIN AD24 [get_ports {segment[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[6]}]
#set_property PACKAGE_PIN AD23 [get_ports {segment[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[5]}]
#set_property PACKAGE_PIN Y21 [get_ports {segment[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[4]}]
#set_property PACKAGE_PIN W20 [get_ports {segment[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[3]}]
#set_property PACKAGE_PIN AC24 [get_ports {segment[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[2]}]
#set_property PACKAGE_PIN AC23 [get_ports {segment[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[1]}]
#set_property PACKAGE_PIN AA22 [get_ports {segment[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {segment[0]}]

#TriLed
set_property PACKAGE_PIN U21 [get_ports {readn}]
set_property IOSTANDARD LVCMOS33 [get_ports {readn}]
set_property PACKAGE_PIN U22 [get_ports {RDY}]
set_property IOSTANDARD LVCMOS33 [get_ports {RDY}]
set_property PACKAGE_PIN V22 [get_ports {CR}]
set_property IOSTANDARD LVCMOS33 [get_ports {CR}]
#set_property PACKAGE_PIN U24 [get_ports {TriLedR1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {TriLedR1}]
#set_property PACKAGE_PIN U25 [get_ports {TriLedG1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {TriLedG1}]
#set_property PACKAGE_PIN V23 [get_ports {TriLedB1}]
#set_property IOSTANDARD LVCMOS33 [get_ports {TriLedB1}]

set_property PACKAGE_PIN V17 [get_ports {K_ROW[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_ROW[0]}]
set_property PACKAGE_PIN W18 [get_ports {K_ROW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_ROW[1]}]
set_property PACKAGE_PIN W19 [get_ports {K_ROW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_ROW[2]}]
set_property PACKAGE_PIN W15 [get_ports {K_ROW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_ROW[3]}]
set_property PACKAGE_PIN W16 [get_ports {K_ROW[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_ROW[4]}]

set_property PACKAGE_PIN V18 [get_ports {K_COL[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_COL[0]}]
set_property PACKAGE_PIN V19 [get_ports {K_COL[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_COL[1]}]
set_property PACKAGE_PIN V14 [get_ports {K_COL[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_COL[2]}]
set_property PACKAGE_PIN W14 [get_ports {K_COL[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {K_COL[3]}]

#set_property PACKAGE_PIN M24 [get_ports segClk]
#set_property IOSTANDARD LVCMOS33 [get_ports segClk]
#set_property PACKAGE_PIN M20 [get_ports segCtr_n]
#set_property IOSTANDARD LVCMOS33 [get_ports segCtr_n]
#set_property PACKAGE_PIN L24 [get_ports segdo]
#set_property IOSTANDARD LVCMOS33 [get_ports segdo]
#set_property PACKAGE_PIN R18 [get_ports segpen]
#set_property IOSTANDARD LVCMOS33 [get_ports segpen]
#set_property PACKAGE_PIN N26 [get_ports ledClk]
#set_property IOSTANDARD LVCMOS33 [get_ports ledClk]
#set_property PACKAGE_PIN N24 [get_ports ledCtr_n]
#set_property IOSTANDARD LVCMOS33 [get_ports ledCtr_n]
#set_property PACKAGE_PIN M26 [get_ports lendo]
#set_property IOSTANDARD LVCMOS33 [get_ports lendo]
#set_property PACKAGE_PIN P18 [get_ports lenpen]
#set_property IOSTANDARD LVCMOS33 [get_ports lenpen]
#Aduio
#set_property PACKAGE_PIN P26 [get_ports audPWM]
#set_property IOSTANDARD LVCMOS33 [get_ports audPWM]
#set_property PACKAGE_PIN M25 [get_ports audSd]
#set_property IOSTANDARD LVCMOS33 [get_ports audSd]
#Red
set_property PACKAGE_PIN N21 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property SLEW FAST [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN N22 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property SLEW FAST [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN R21 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property SLEW FAST [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN P21 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property SLEW FAST [get_ports {VGA_R[3]}]
#Green
set_property PACKAGE_PIN R22 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property SLEW FAST [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN R23 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property SLEW FAST [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN T24 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property SLEW FAST [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN T25 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property SLEW FAST [get_ports {VGA_G[3]}]
#Blue
set_property PACKAGE_PIN T20 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property SLEW FAST [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN R20 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property SLEW FAST [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN T22 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property SLEW FAST [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN T23 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property SLEW FAST [get_ports {VGA_B[3]}]



set_property PACKAGE_PIN M22 [get_ports HS]
set_property IOSTANDARD LVCMOS33 [get_ports HS]
set_property SLEW FAST [get_ports HS]
set_property PACKAGE_PIN M21 [get_ports VS]
set_property IOSTANDARD LVCMOS33 [get_ports VS]
set_property SLEW FAST [get_ports VS]


#set_property PACKAGE_PIN N18 [get_ports ps2clk]
#set_property IOSTANDARD LVCMOS33 [get_ports ps2clk]
#set_property PULLUP true [get_ports ps2clk]
#set_property PACKAGE_PIN M19 [get_ports ps2dat]
#set_property IOSTANDARD LVCMOS33 [get_ports ps2dat]
#set_property PULLUP true [get_ports ps2dat]