# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vivado/audio/audio.cache/wt [current_project]
set_property parent.project_path F:/vivado/audio/audio.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/vivado/audio/audio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/vivado/audio/audio.srcs/sources_1/new/audio.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/vivado/audio/audio.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files F:/vivado/audio/audio.srcs/constrs_1/new/xdc.xdc]


synth_design -top audio -part xc7k160tfbg676-2L


write_checkpoint -force -noxdef audio.dcp

catch { report_utilization -file audio_utilization_synth.rpt -pb audio_utilization_synth.pb }
