# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vivado/vga/vga.cache/wt [current_project]
set_property parent.project_path F:/vivado/vga/vga.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/vivado/vga/vga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/vivado/vga/vga.srcs/sources_1/x.coe
add_files -quiet F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.dcp
set_property used_in_implementation false [get_files F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.dcp]
read_verilog -library xil_defaultlib {
  F:/vivado/vga/vga.srcs/sources_1/new/vgaSync.v
  F:/vivado/vga/vga.srcs/sources_1/new/clkdiv.v
  F:/vivado/vga/vga.srcs/sources_1/new/vga.v
  F:/vivado/vga/vga.srcs/sources_1/new/top_vga.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/vivado/vga/vga.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files F:/vivado/vga/vga.srcs/constrs_1/new/xdc.xdc]


synth_design -top top_vga -part xc7k160tfbg676-2L


write_checkpoint -force -noxdef top_vga.dcp

catch { report_utilization -file top_vga_utilization_synth.rpt -pb top_vga_utilization_synth.pb }
