webtalk_init -webtalk_dir /home/lovesy/Documents/Learning/CA/EXP5_Vivado/EXP5_Vivado.sim/sim_1/behav/xsim/xsim.dir/CacheTest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 30 12:27:56 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d1a39b8b-b178-45b8-8a41-1d7f0894e0b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4a4a6d27389a45be9ab4357d8a2618c2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "48" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1975.860 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2296681447 -regid "" -xml /home/lovesy/Documents/Learning/CA/EXP5_Vivado/EXP5_Vivado.sim/sim_1/behav/xsim/xsim.dir/CacheTest_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/lovesy/Documents/Learning/CA/EXP5_Vivado/EXP5_Vivado.sim/sim_1/behav/xsim/xsim.dir/CacheTest_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/lovesy/Documents/Learning/CA/EXP5_Vivado/EXP5_Vivado.sim/sim_1/behav/xsim/xsim.dir/CacheTest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
