# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vivado/ps2Mouse/ps2Mouse.cache/wt [current_project]
set_property parent.project_path F:/vivado/ps2Mouse/ps2Mouse.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/vivado/ps2Mouse/ps2Mouse.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/vivado/ps2Mouse/ps2Mouse.srcs/sources_1/new/readMouse.v
  F:/vivado/ps2Mouse/ps2Mouse.srcs/sources_1/new/initMouse.v
  F:/vivado/ps2Mouse/ps2Mouse.srcs/sources_1/new/PS2Mouse.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top PS2Mouse -part xc7k160tfbg676-2L


write_checkpoint -force -noxdef PS2Mouse.dcp

catch { report_utilization -file PS2Mouse_utilization_synth.rpt -pb PS2Mouse_utilization_synth.pb }
