# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/winprompt/winprompt.xci
# IP: The module: 'winprompt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/winprompt/winprompt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'winprompt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/winprompt/winprompt.xci
# IP: The module: 'winprompt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Shana/Desktop/vivado/NestGather/NestGather.srcs/sources_1/ip/winprompt/winprompt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'winprompt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
