# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.xci
# IP: The module: 'vram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.xci
# IP: The module: 'vram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
