# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7k160tfbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/vivado/vga/vga.cache/wt [current_project]
set_property parent.project_path F:/vivado/vga/vga.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/vivado/vga/vga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.xci
set_property is_locked true [get_files F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir F:/vivado/vga/vga.runs/vram_synth_1 -new_name vram -ip [get_ips vram]]

if { $cached_ip eq {} } {

synth_design -top vram -part xc7k160tfbg676-2L -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix vram_ vram.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vram_stub.v
 lappend ipCachedFiles vram_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vram_stub.vhdl
 lappend ipCachedFiles vram_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vram_sim_netlist.v
 lappend ipCachedFiles vram_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vram_sim_netlist.vhdl
 lappend ipCachedFiles vram_sim_netlist.vhdl

 config_ip_cache -add -dcp vram.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips vram]
}

rename_ref -prefix_all vram_

write_checkpoint -force -noxdef vram.dcp

catch { report_utilization -file vram_utilization_synth.rpt -pb vram_utilization_synth.pb }

if { [catch {
  file copy -force F:/vivado/vga/vga.runs/vram_synth_1/vram.dcp F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force F:/vivado/vga/vga.runs/vram_synth_1/vram.dcp F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force F:/vivado/vga/vga.runs/vram_synth_1/vram_stub.v F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/vivado/vga/vga.runs/vram_synth_1/vram_stub.vhdl F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/vivado/vga/vga.runs/vram_synth_1/vram_sim_netlist.v F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force F:/vivado/vga/vga.runs/vram_synth_1/vram_sim_netlist.vhdl F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir F:/vivado/vga/vga.ip_user_files/ip/vram]} {
  catch { 
    file copy -force F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_stub.v F:/vivado/vga/vga.ip_user_files/ip/vram
  }
}

if {[file isdir F:/vivado/vga/vga.ip_user_files/ip/vram]} {
  catch { 
    file copy -force F:/vivado/vga/vga.srcs/sources_1/ip/vram/vram_stub.vhdl F:/vivado/vga/vga.ip_user_files/ip/vram
  }
}
