# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ROM_D/ROM_D.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_D || ORIG_REF_NAME==ROM_D}]

# IP: ip/RAM_B/RAM_B.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B}]
