webtalk_init -webtalk_dir D:/Users/Shana/Desktop/EXP5/vivado/vivado.sim/sim_1/synth/func/xsim.dir/Main_Main_sch_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 11 15:34:06 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "554018cd-2bdd-4a02-b02f-b9ed4b4cfc8a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c578b66a4a4c4e9fb4613d7794d0c52f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2694 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "18178175100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "7" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1011.81_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "49856_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2609300078 -regid "" -xml D:/Users/Shana/Desktop/EXP5/vivado/vivado.sim/sim_1/synth/func/xsim.dir/Main_Main_sch_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/Users/Shana/Desktop/EXP5/vivado/vivado.sim/sim_1/synth/func/xsim.dir/Main_Main_sch_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/Users/Shana/Desktop/EXP5/vivado/vivado.sim/sim_1/synth/func/xsim.dir/Main_Main_sch_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
